### PR TITLE
updates @mozilla/glean to 0.14.1

### LINKED ISSUE #106: Integrate Glean.js
This issue is for integrating Glean.js and bringing the Glean-powered data to parity with the current one collected with legacy telemetry.

### PR DESCRIPTION
**Pull request by hamilton**
closes #106

### CODE REVIEW

**Comment by hamilton** [comment]
@Dexterp37 I'm seeing that now, there seems to be an issue with the unit tests in RS01 and Glean. I think the same issue existed in the previous PR, but I didn't see the test failure before. Any ideas about why this might be failing?

**Comment by rhelmer** [comment]
> The unit tests fail with glean in `study.js`. Will keep looking since I think this is a jest issue colliding with glean.
> 
> The solution might look like [`moduleNameMapper`](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring) but need to look into it more.

I have tests passing locally, but I found a number of problems:

1. `moduleNameMapper` does help, but I'd like to understand why we need it... AFAICT `jest` tries to use `babel` automatically as long as a config file is present, and it works OK for `@mozilla/rally` package:

```
    "moduleNameMapper": {
      "^@mozilla/glean/webext$": "<rootDir>/node_modules/@mozilla/glean/dist/webext/index/webext.js",
      "^@mozilla/glean/webext/plugins/encryption$": "<rootDir>/node_modules/@mozilla/glean//dist/webext/plugins/encryption.js",
      "^@mozilla/glean/webext/private/metrics/datetime$": "<rootDir>/node_modules/@mozilla/glean/dist/webext/core/metrics/types/datetime.js",
      "^@mozilla/glean/webext/private/metrics/quantity$": "<rootDir>/node_modules/@mozilla/glean/dist/webext/core/metrics/types/quantity.js",
      "^@mozilla/glean/webext/private/metrics/string$": "<rootDir>/node_modules/@mozilla/glean/dist/webext/core/metrics/types/string.js",
      "^@mozilla/glean/webext/private/metrics/timespan$": "<rootDir>/node_modules/@mozilla/glean/dist/webext/core/metrics/types/timespan.js",
      "^@mozilla/glean/webext/private/ping$": "<rootDir>/node_modules/@mozilla/glean/dist/webext/core/internal_pings.js",
      "^jose/jwe/compact/encrypt$": "<rootDir>/node_modules/jose/dist/node/cjs/jwe/compact/encrypt.js",
      "^jose/jwk/parse": "<rootDir>/node_modules/jose/dist/node/cjs/jwk/parse.js",
      "^jose/jwk/thumbprint": "<rootDir>/node_modules/jose/dist/node/cjs/jwk/thumbprint.js"
    },
```
2. `TextEncoder` and `TextDecoder` are not defined, maybe there's an easier way but I just mocked them out using the `testEnvironment` `jest` config key.
3. Glean is throwing an error about `browser.runtime.getPlatformInfo()` not being a function here: https://github.com/mozilla/glean.js/blob/a635b7df1d605235fd6a5b01c50048fd4029ccc9/glean/src/platform/webext/platform_info.ts#L11 - I just stubbed this out locally and everything else seems to work, not sure what's missing there, I've updated `webextension-polyfill` to the latest version and no difference.
4. Glean is `console.error`ing a few things from its storage module:
```
Error executing task: TypeError: Cannot read property 'appLifetimeMetrics' of undefined
[...]
Error executing task: TypeError: Cannot read property 'userLifetimeMetrics' of undefined
```

However! All that said, with 1/2/3 above, the tests do pass (I'm not sure what the impact of (4) is), @Dexterp37 any thoughts on the above? I don't know why we need to map the module names and why `jest` doesn't pick them up from the paths in `package.json` for `glean` and `jose`, since these obviously work fine when importing normally. I suspect it's something `jest`-specific that we have a workaround and can track that down separately ((1) above). The more important ones seem to me to be (3) and (4).

Here's a successful test run:
```
% npm run test:unit

> rally-study-01@0.1.5 test:unit
> jest

 PASS  tests/unit/attention-reporter.test.js
  attention-reporter
    startMeasurement
      ✓ initializes the PageManager module (3 ms)
      ✓ registers a new content script
      ✓ registers the RS01.attentionCollection and RS01.audioCollection events (1 ms)
    stopMeasurement
      ✓ unregisters the RS01.attentionCollection and RS01.audioCollection events (1 ms)
      ✓ unregisters the content script

 PASS  tests/unit/study.test.js
  study.js
    ✓ successfully initializes a Rally instance (8 ms)
    ✓ successfully calls AttentionReporter.onPageData on initialization (3 ms)
    ✓ calls stopMeasurement if the rally instance receives a "pause" message (1 ms)

Test Suites: 2 passed, 2 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        3.009 s
Ran all test suites.
  console.error
    Error executing task: TypeError: Cannot read property 'appLifetimeMetrics' of undefined
        at WebExtStore._callee$ (/Users/mozilla/src/rally-study-01/node_modules/@mozilla/glean/dist/webext/platform/webext/storage.js:76:56)
        at tryCatch (/Users/mozilla/src/rally-study-01/node_modules/regenerator-runtime/runtime.js:70:17)
        at Generator.invoke [as _invoke] (/Users/mozilla/src/rally-study-01/node_modules/regenerator-runtime/runtime.js:287:22)
        at Generator.next (/Users/mozilla/src/rally-study-01/node_modules/regenerator-runtime/runtime.js:123:21)
        at asyncGeneratorStep (/Users/mozilla/src/rally-study-01/node_modules/@babel/runtime/helpers/asyncToGenerator.js:5:24)
        at _next (/Users/mozilla/src/rally-study-01/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

      at _callee$ (node_modules/@mozilla/glean/dist/webext/core/dispatcher.js:70:25)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:70:17)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:287:22)
      at Generator.throw (node_modules/regenerator-runtime/runtime.js:123:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:5:24)
      at _throw (node_modules/@babel/runtime/helpers/asyncToGenerator.js:31:9)

  console.error
    Error executing task: TypeError: Cannot read property 'userLifetimeMetrics' of undefined
        at WebExtStore._callee$ (/Users/mozilla/src/rally-study-01/node_modules/@mozilla/glean/dist/webext/platform/webext/storage.js:76:56)
        at tryCatch (/Users/mozilla/src/rally-study-01/node_modules/regenerator-runtime/runtime.js:70:17)
        at Generator.invoke [as _invoke] (/Users/mozilla/src/rally-study-01/node_modules/regenerator-runtime/runtime.js:287:22)
        at Generator.next (/Users/mozilla/src/rally-study-01/node_modules/regenerator-runtime/runtime.js:123:21)
        at asyncGeneratorStep (/Users/mozilla/src/rally-study-01/node_modules/@babel/runtime/helpers/asyncToGenerator.js:5:24)
        at _next (/Users/mozilla/src/rally-study-01/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:9)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

      at _callee$ (node_modules/@mozilla/glean/dist/webext/core/dispatcher.js:70:25)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:70:17)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:287:22)
      at Generator.throw (node_modules/regenerator-runtime/runtime.js:123:21)
      at asyncGeneratorStep (node_modules/@babel/runtime/helpers/asyncToGenerator.js:5:24)
      at _throw (node_modules/@babel/runtime/helpers/asyncToGenerator.js:31:9)
```

**Comment by Dexterp37** [comment]
Thanks for the investigation @rhelmer . Let me take a look.

**Comment by Dexterp37** [comment]
> I have tests passing locally, but I found a number of problems:
> 
>     1. `moduleNameMapper` does help, but I'd like to understand why we need it... AFAICT `jest` tries to use `babel` automatically as long as a config file is present, and it works OK for `@mozilla/rally` package:

It looks like Jest has the [following limitation](https://jestjs.io/docs/configuration#modulenamemapper-objectstring-string--arraystring):

> Modules that are mapped to an alias are unmocked by default, regardless of whether automocking is enabled or not.

That explains why [Glean.js](https://github.com/mozilla/glean.js/blob/b709147898f900b9031ccb44676df8aca63561b5/glean/src/index/webext.ts#L10) isn't mocked while [rally.js](https://github.com/mozilla-rally/rally-core-addon/blob/42de43a286b2d9edd551b942ab6f4e249b0bdc41/support/rally.js#L13) is. So I think that your mapping, Rob, fixes the biggest problem. 

I'm taking a look at the rest of the issues. Sadly running this test suite takes ~1 minute on my machine because ... Jest doesn't like Windows :-)

**Comment by Dexterp37** [comment]
>     1. `TextEncoder` and `TextDecoder` are not defined, maybe there's an easier way but I just mocked them out using the `testEnvironment` `jest` config key.

This seems to be [another issue with Jest](https://github.com/jsdom/jsdom/issues/2524#issuecomment-736672511).

**Review by rhelmer — APPROVED** [review]

**Comment by hamilton** [comment]
Thanks for looking into this @Dexterp37 and @rhelmer! Merging now.

**Pull request merged**
